name: build

on:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y libc6-dev libgcc-8-dev libstdc++-8-dev
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Add targets
        run: rustup target add x86_64-unknown-linux-gnu && rustup target add i686-unknown-linux-gnu
      - name: Build 32-bit
        run: export CC=$(which gcc) && cargo build --release --target i686-unknown-linux-gnu
      - name: Build 64-bit
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Strip debug symbols
        run: |
          strip target/i686-unknown-linux-gnu/release/libgmsv_mongo.so
          strip target/x86_64-unknown-linux-gnu/release/libgmsv_mongo.so
      - name: Rename binaries
        run: |
          mv target/i686-unknown-linux-gnu/release/libgmsv_mongo.so target/i686-unknown-linux-gnu/release/gmsv_mongo_linux.dll
          mv target/x86_64-unknown-linux-gnu/release/libgmsv_mongo.so target/x86_64-unknown-linux-gnu/release/gmsv_mongo_linux64.dll
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/i686-unknown-linux-gnu/release/gmsv_mongo_linux.dll
            target/x86_64-unknown-linux-gnu/release/gmsv_mongo_linux64.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - name: Add targets
        run: rustup target add x86_64-pc-windows-msvc && rustup target add i686-pc-windows-msvc
      - name: Build 64-bit
        run: cargo build --release --target x86_64-pc-windows-msvc
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static
      - name: Build 32-bit
        run: cargo build --release --target i686-pc-windows-msvc
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static
      - name: Rename binaries
        run: |
          mv target/i686-pc-windows-msvc/release/gmsv_mongo.dll target/i686-pc-windows-msvc/release/gmsv_mongo_win32.dll
          mv target/x86_64-pc-windows-msvc/release/gmsv_mongo.dll target/x86_64-pc-windows-msvc/release/gmsv_mongo_win64.dll
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/i686-pc-windows-msvc/release/gmsv_mongo_win32.dll
            target/x86_64-pc-windows-msvc/release/gmsv_mongo_win64.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}