name: Rust Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create .env
      run: echo "MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}" > .env
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
